# ---------- BUILD ----------
FROM eclipse-temurin:17-jdk AS build
WORKDIR /app
ENV GRADLE_OPTS="-Dorg.gradle.wrapper.downloadTimeout=120000"
COPY gradle gradle
COPY gradlew settings.gradle build.gradle ./
RUN chmod +x gradlew && ./gradlew dependencies --no-daemon || true
COPY src src
RUN ./gradlew bootJar --no-daemon -x test

# ---------- RUN ----------
FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE 8989
ENTRYPOINT ["java", "-jar", "app.jar"]